parameters:
- name: PYTHON_VERSION 
  type: string
  default: "3.11"



stages:
  - stage: Build
    jobs:
      - job: Build archive
        pool:
          vmImage: ubuntu-latest      
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '${{ parameters.PYTHON_VERSION }}'
            displayName: 'Use Python ${{ parameters.PYTHON_VERSION }}'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install dependencies'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: $(System.DefaultWorkingDirectory)
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-${{ parameters.PYTHON_VERSION }}.zip
              replaceExistingArchive: true
      - job: Publish archvie        
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  - stage: Test
    jobs:
      - job: Test
        steps:
          - script: |
              pip install pytest pytest-azurepipelines
              pytest
            displayName: 'pytest'