trigger:
  branches:
    include:
      - main
      - master

# Microsoft-Hosted agents
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout Repository'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Set up Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    cd service1 && pip install -r requirements.txt && cd ..
    cd service2 && pip install -r requirements.txt && cd ..
  displayName: 'Install Dependencies'

- script: |
    pytest --maxfail=1 --disable-warnings -q
  displayName: 'Run Unit Tests'