version: '3.8'

services:
  service1:
    build:
      context: ./service1
    ports:
      - "5001:5000"
    networks:
      - my-network

  service2:
    build:
      context: ./service2
    ports:
      - "5002:5000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge